// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_4ynD5Q-4VXa_wEWX3Ru5SmQMCGAdcPY',
    appId: '1:271256759287:web:74b1028a4d9d7c83fa9cf2',
    messagingSenderId: '271256759287',
    projectId: 'savir-15-1-2003',
    authDomain: 'savir-15-1-2003.firebaseapp.com',
    storageBucket: 'savir-15-1-2003.firebasestorage.app',
    measurementId: 'G-WSE8EG9J8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw3h3YBMUywHnhSEaGM0TYc6Nj_9LCWfk',
    appId: '1:271256759287:android:428b884bd2e4afa8fa9cf2',
    messagingSenderId: '271256759287',
    projectId: 'savir-15-1-2003',
    storageBucket: 'savir-15-1-2003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj8_1fKn-gpSgDZNGCQPmv95PG0gFTnts',
    appId: '1:271256759287:ios:d8fda110bfe9743ffa9cf2',
    messagingSenderId: '271256759287',
    projectId: 'savir-15-1-2003',
    storageBucket: 'savir-15-1-2003.firebasestorage.app',
    iosBundleId: 'com.ecommerce.savirtechnology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj8_1fKn-gpSgDZNGCQPmv95PG0gFTnts',
    appId: '1:271256759287:ios:d8fda110bfe9743ffa9cf2',
    messagingSenderId: '271256759287',
    projectId: 'savir-15-1-2003',
    storageBucket: 'savir-15-1-2003.firebasestorage.app',
    iosBundleId: 'com.ecommerce.savirtechnology',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_4ynD5Q-4VXa_wEWX3Ru5SmQMCGAdcPY',
    appId: '1:271256759287:web:b5c6d9e357506b5dfa9cf2',
    messagingSenderId: '271256759287',
    projectId: 'savir-15-1-2003',
    authDomain: 'savir-15-1-2003.firebaseapp.com',
    storageBucket: 'savir-15-1-2003.firebasestorage.app',
    measurementId: 'G-F9C0FB8VFL',
  );
}
