// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1J8tCFHmleQHqkeS4stUZvmP6tzEkKUg',
    appId: '1:134501745798:web:810e256c57676ca6927d07',
    messagingSenderId: '134501745798',
    projectId: 'percious-fragance-664bc',
    authDomain: 'percious-fragance-664bc.firebaseapp.com',
    storageBucket: 'percious-fragance-664bc.firebasestorage.app',
    measurementId: 'G-8LV38KLR6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf4ViGDrugT3r6tG_14fyMoAmJpz104XM',
    appId: '1:134501745798:android:0f32e59cec15ba91927d07',
    messagingSenderId: '134501745798',
    projectId: 'percious-fragance-664bc',
    storageBucket: 'percious-fragance-664bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9EX9AEIRY1Nk14qYfUqv60i38jAF_Fn0',
    appId: '1:134501745798:ios:1d50f5f5f8a9f238927d07',
    messagingSenderId: '134501745798',
    projectId: 'percious-fragance-664bc',
    storageBucket: 'percious-fragance-664bc.firebasestorage.app',
    iosClientId: '134501745798-rnkstvg28f10dtp0k7a0fh308olrlgjc.apps.googleusercontent.com',
    iosBundleId: 'com.savir.per',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9EX9AEIRY1Nk14qYfUqv60i38jAF_Fn0',
    appId: '1:134501745798:ios:1d50f5f5f8a9f238927d07',
    messagingSenderId: '134501745798',
    projectId: 'percious-fragance-664bc',
    storageBucket: 'percious-fragance-664bc.firebasestorage.app',
    iosClientId: '134501745798-rnkstvg28f10dtp0k7a0fh308olrlgjc.apps.googleusercontent.com',
    iosBundleId: 'com.savir.per',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1J8tCFHmleQHqkeS4stUZvmP6tzEkKUg',
    appId: '1:134501745798:web:c2fa71f17e3ccb65927d07',
    messagingSenderId: '134501745798',
    projectId: 'percious-fragance-664bc',
    authDomain: 'percious-fragance-664bc.firebaseapp.com',
    storageBucket: 'percious-fragance-664bc.firebasestorage.app',
    measurementId: 'G-6Q1VX7LTP1',
  );

}