import 'package:get/get.dart';

class MyTranslation extends Translations {
  static const Map<String, String> _arOverrides = {
    'comment': 'تعليق',
    'comments': 'التعليقات',
    'no_comments_yet': 'لا توجد تعليقات بعد',
    'leave_your_comment': 'اترك تعليقك',
    'comments_items': 'تعليق',
    'start_conversation_reel': 'ابدأ المحادثة وشارك رأيك حول هذا الريلز.',
    'replying_to': 'الرد على',
    'write_comment': 'اكتب تعليقًا...',
    'reply': 'رد',
  };

  @override
  Map<String, Map<String, String>> get keys {
    final map = {
      'ar': {
        '1': 'اختر اللغة',
        '2': 'سافير',
        '3': 'مرحبًا بك في تطبيق سافير تكنولوجي!',
        '4': 'تتبع طلباتك',
        '5': 'يمكنك تتبع طلباتك وأنت جالس على الأريكة.',
        'o2': 'أسرع خدمة توصيل',
        'o3': 'خدمة موثوقة وسريعة وآمنة\nنوصل منتجاتك بأسرع طريقة ممكنة',
        '8': 'متابعة',
        '9': 'تسجيل الدخول',
        '10': 'مرحبًا بعودتك',
        'o10': 'كلمة المرور',
        '11': 'يمكنك تسجيل الدخول باستخدام البريد الإلكتروني وكلمة المرور',
        '12': 'أدخل بريدك الإلكتروني',
        'o12': 'البريد الإلكتروني',
        'oo12': 'أدخل البريد الإلكتروني',
        '13': 'أدخل كلمة المرور',
        'o13': 'أدخل كلمة المرور',
        '14': 'هل نسيت كلمة المرور؟',
        'o14': 'إعادة إدخال كلمة المرور',
        '15': 'تسجيل الدخول',
        '16': 'ليس لديك حساب؟',
        '17': 'إنشاء حساب',
        '18': 'البريد الإلكتروني',
        '19': 'كلمة المرور',
        '20': 'اسم المستخدم',
        'o20': 'مرحبًا بك في صفحة التسجيل',
        'o21': 'في هذه الصفحة يمكنك إنشاء حساب بملء الحقول أدناه',
        '21': 'رقم الهاتف',
        '22': 'أدخل رقم الهاتف',
        '23': 'أدخل اسم المستخدم',
        '24':
            'أنشئ حسابًا باستخدام البريد الإلكتروني وكلمة المرور أو وسائل التواصل الاجتماعي',
        '25': 'لديك حساب بالفعل؟',
        '26': 'تسجيل الدخول',
        '27': 'تحقق من بريدك الإلكتروني',
        '28': 'تم إنشاء الحساب بنجاح',
        '29': 'يرجى إدخال بريدك الإلكتروني لاستلام رمز التحقق',
        '30': 'تحقق',
        '31': 'اذهب لتسجيل الدخول',
        '32': 'نجاح',
        '33': 'حفظ',
        '34': 'يرجى إدخال كلمة المرور الجديدة',
        '35': 'كلمة مرور جديدة',
        '36': 'تم إعادة تعيين كلمة المرور بنجاح',
        '37': 'تهانينا',
        '38': 'تم التسجيل بنجاح',
        '39': 'اسم غير صالح',
        '40': 'بريد إلكتروني غير صالح',
        '41': 'رقم هاتف غير صالح',
        '42': 'المحتوى قصير جدًا',
        '43': 'المحتوى طويل جدًا',
        '44': 'الحقل لا يمكن أن يكون فارغًا',
        '45': 'هل نسيت كلمة المرور؟',
        '46': 'إعادة تعيين كلمة المرور',
        '47': 'حفظ',
        '48': 'أدخل كلمة مرور جديدة',
        '49': 'خذ نفسًا وكن صبورًا',
        '50': 'أحسنت!',
        '51': 'حاول مرة أخرى',
        '52': 'النظام يواجه مشكلة',
        '53': 'اذهب إلى مدام حنان في الدور الثاني',
        '54': 'أعد الشحن وارجع مرة أخرى',
        '55': 'الفئات',
        '56': 'الأكثر مبيعًا',
        '57': 'الخصومات',
        '58': 'مرحبًا ',
        '59': 'نتمنى لك تجربة ممتازة',
        '60': 'سافير',
        '61': 'مصر',
        '62': 'غير متوفر حاليًا',
        '63': 'الوصف',
        '64': 'إضافة إلى السلة',
        '65': 'نسخ الكوبون',
        '66': 'موافق',
        '67': 'عجلة الحظ',
        '68': 'لفة مجانية كل 12 ساعة - فرصة ربح 25%',
        '69': 'ابدأ اللف',
        '70': 'ابحث هنا...',
        '71': 'الإعدادات',
        '72': 'اللغة العربية',
        '73': 'العربية',
        '74': 'العنوان',
        '75': 'إدارة العناوين',
        '76': 'من نحن',
        '77': 'تعرف على التطبيق',
        '78': 'أرشيف الطلبات',
        '79': 'الطلبات السابقة',
        '80': 'اللغة الإنجليزية',
        '81': 'الإنجليزية',
        '83': 'مرحبًا،',
        '84': 'اختر عنوان التوصيل',
        '85': 'تسجيل الخروج',
        '87': 'خطأ',
        '88': 'إلغاء',
        '89': 'تأكيد',
        '90': 'حذف',
        '91': 'تطبيق',
        '92': 'عناصرك',
        '95': 'الكمية',
        '96': 'السعر',
        '97': 'السعر الإجمالي',
        '98': 'عنوان الشحن',
        '99': 'تفاصيل الطلب',
        '100': 'رقم الطلب',
        '101': 'سعر الطلب',
        '102': 'سعر التوصيل',
        '103': 'طريقة الدفع',
        '106': 'السعر النهائي',
        '108': 'إتمام الطلب',
        '109': 'راجع التفاصيل قبل الدفع',
        '110': 'الإجمالي',
        '111': 'تأكيد الطلب',
        '112': 'تعليقات',
        '114': 'لا توجد تعليقات بعد',
        '115': 'كن أول من يعلق ويشارك رأيه',
        '116': 'أضف تعليق الآن',
        '117': 'الحالة',
        '120': 'مفضلاتي',
        '122': 'هل لديك كوبون؟',
        '123': 'أدخل رمز الكوبون',
        '124': 'السلة',
        '126': 'سلتك فارغة',
        '127': 'الإجمالي الفرعي',
        '128': 'خصومات المنتجات',
        '129': 'خصم الكوبون',
        '130': 'الإجمالي النهائي',
        '131': 'تأكيد',
        '132': 'هل تريد حذف هذا المنتج من السلة؟',
        '134': 'تحذير',
        '135': 'يرجى إضافة عنوان شحن قبل إتمام الطلب',
        'store': 'المتجر',
        'browse_all_products': 'تصفح جميع المنتجات',
        'find_product': 'ابحث عن منتج',
        'available': 'متوفر',
        'featured_now': 'مميز الآن',
        'out_of_stock': 'غير متوفر',
        'discount_available': 'يوجد خصم',
        'secure_shopping': 'تسوق آمن',
        'fast_delivery': 'توصيل سريع',
        'best_prices': 'أفضل الأسعار',
        'popular_products': 'منتجات شائعة',
        'view_all': 'عرض الكل',
        'shop_now': 'تسوق الآن',
        'new_collection': 'مجموعة جديدة',
        'profile_title': 'الملف الشخصي',
        'notifications_title': 'الإشعارات',
        'no_notifications_yet': 'لا توجد إشعارات بعد',
        'search': 'بحث',
        'special_offers': 'عروض خاصة',
        'checkout': 'إتمام الشراء',
        'product_details': 'تفاصيل المنتج',
        'support': 'الدعم',
        'favorites': 'المفضلة',
        'home': 'الرئيسية',
        'comment': 'تعليق',
        'comments': 'التعليقات',
        'success_signup_title': 'تم إنشاء الحساب',
        'success_reset_password_title': 'تم تغيير كلمة المرور',
        'go_to_login': 'اذهب لتسجيل الدخول',
        'Home': 'الرئيسية',
        'Community': 'المجتمع',
        'Builder': 'المنشئ',
        'Chat': 'الدردشة',
        'Cart': 'السلة',
        'Shopping Cart': 'سلة التسوق',
        'Proceed to Checkout': 'المتابعة للدفع',
        'Precious Collection': 'مجموعة بريشيوس',
        'Precious Fragrance': 'بريشيوس فراجرانس',
        'Custom Perfume': 'عطر مخصص',
        'Promo Code': 'كود الخصم',
        'Enter code': 'أدخل الكود',
        'applied': 'تم التطبيق',
        'off': 'خصم',
        'Order Summary': 'ملخص الطلب',
        'Subtotal': 'الإجمالي الفرعي',
        'Shipping': 'الشحن',
        'Savings': 'التوفير',
        'Place Order': 'تنفيذ الطلب',
        'Add Address': 'إضافة عنوان',
        'Delivery Options': 'خيارات التوصيل',
        'Standard Delivery': 'توصيل عادي',
        'Express Delivery': 'توصيل سريع',
        'Premium Delivery': 'توصيل مميز',
        'Cash on Delivery': 'الدفع عند الاستلام',
        'Credit Card': 'بطاقة ائتمان',
        'Find your fragrance': 'ابحث عن عطرك',
        'Discover Your Signature Scent': 'اكتشف عطرك المميز',
        'Fragrances Available': 'العطور المتوفرة',
        'ok': 'موافق'
      },
      'en': {
        '1': 'Choose Language',
        '2': 'Savir',
        '3': 'Welcome to Savir Technology App!',
        '4': 'Track your orders',
        '5': 'You can track your orders while sitting on your couch.',
        'o2': 'Fastest Delivery Service',
        'o3':
            'Reliable, fast, and safe delivery\nWe deliver your products in the quickest way possible',
        '8': 'Continue',
        '9': 'Login',
        '10': 'Welcome Back',
        'o10': 'Password',
        '11': 'You can log in using your email and password',
        '12': 'Enter your email',
        'o12': 'Email',
        'oo12': 'Enter email',
        '13': 'Enter your password',
        'o13': 'Enter password',
        '14': 'Forgot your password?',
        'o14': 'Re-enter password',
        '15': 'Login',
        '16': "Don't have an account?",
        '17': 'Create Account',
        '18': 'Email',
        '19': 'Password',
        '20': 'Username',
        'o20': 'Welcome to the registration page',
        'o21':
            'On this page, you can create an account by filling in the fields below',
        '21': 'Phone Number',
        '22': 'Enter phone number',
        '23': 'Enter username',
        '24': 'Create an account using email and password or social media',
        '25': 'Already have an account?',
        '26': 'Login',
        '27': 'Check your email',
        '28': 'Account created successfully',
        '29': 'Please enter your email to receive the verification code',
        '30': 'Check',
        '31': 'Go to Login',
        '32': 'Success',
        '33': 'Save',
        '34': 'Please enter your new password',
        '35': 'New Password',
        '36': 'Password reset successfully',
        '37': 'Congratulations',
        '38': 'Registration successful',
        '39': 'Invalid name',
        '40': 'Invalid email',
        '41': 'Invalid phone number',
        '42': 'Content is too short',
        '43': 'Content is too long',
        '44': 'Field cannot be empty',
        '45': 'Forgot your password?',
        '46': 'Reset Password',
        '47': 'Save',
        '48': 'Enter a new password',
        '49': 'Take a breath and be patient',
        '50': 'Well done, champ!',
        '51': 'Try again',
        '52': 'The system is not feeling well',
        '53': 'Go to Madam Hanan on the second floor',
        '54': 'Recharge and come back',
        '55': 'Categories',
        '56': 'Best Selling Products',
        '57': 'Discounts',
        '58': 'Welcome ',
        '59': 'We wish you an excellent experience',
        '60': 'Savir',
        '61': 'Egypt',
        '62': 'Currently unavailable',
        '63': 'Description',
        '64': 'Add to Cart',
        '65': 'Copy Coupon',
        '66': 'OK',
        '67': 'Fortune Wheel',
        '68': 'Free spin every 12 hours - 25% chance to win',
        '69': 'Spin Now',
        '70': 'Search here...',
        '71': 'Settings',
        '72': 'Arabic Language',
        '73': 'Arabic',
        '74': 'Address',
        '75': 'Manage addresses',
        '76': 'About us',
        '77': 'Learn about the app',
        '78': 'Orders Archive',
        '79': 'Previous orders',
        '80': 'English Language',
        '81': 'English',
        '82': 'v603.1 â€¢ Â© Savir Technology',
        '83': 'Welcome,',
        '84': 'Select Delivery Address',
        '85': 'Logout',
        '86': 'Could not open WhatsApp',
        '87': 'Error',
        '88': 'Cancel',
        '89': 'Confirm',
        '90': 'Remove',
        '91': 'Apply',
        '92': 'Your Items',
        '93': 'items',
        '94': 'Item',
        '95': 'QTY',
        '96': 'Price',
        '97': 'Total Price',
        '98': 'Shipping Address',
        '99': 'Orders Details',
        '100': 'Order Number',
        '101': 'Order Price',
        '102': 'Delivery Price',
        '103': 'Payment Method',
        '104': 'Total Price',
        '105': 'Details',
        '106': 'Final Price',
        '107': 'Payment',
        '108': 'Complete Order',
        '109': 'Review Details Before Payment',
        '110': 'Total',
        '111': 'Confirm Order',
        '112': 'Comments',
        '113': 'comment',
        '114': 'No comments yet',
        '115': 'Be the first to comment and share your opinion',
        '116': 'Add comment now',
        '117': 'Status',
        '118': 'Quantity',
        '119': 'No videos',
        '120': 'My Favorites',
        '121': 'Orders Archive',
        '122': 'Have a coupon?',
        '123': 'Enter coupon code',
        '124': 'Cart',
        '125': 'item',
        '126': 'Your cart is empty',
        '127': 'Subtotal',
        '128': 'Item discounts',
        '129': 'Coupon discount',
        '130': 'Final total',
        '131': 'Confirm',
        '132': 'Remove this item from cart?',
        '133': 'You can only add 1 unit of this product',
        '134': 'Warning',
        '135': 'Please add a shipping address before checkout',
        '136': 'Offers Page',
        'settings_title': 'Settings',
        'account_label': 'Account',
        'dark_theme': 'Dark theme',
        'switch_theme': 'Switch between light and dark mode',
        'arabic': 'Arabic',
        'use_arabic': 'Use Arabic language',
        'english': 'English',
        'use_english': 'Use English language',
        'address_title': 'Address',
        'address_subtitle': 'Manage delivery details',
        'orders_archive_title': 'Orders archive',
        'orders_archive_subtitle': 'See previous orders',
        'about_app_title': 'About app',
        'about_app_subtitle': 'Learn more about Savir',
        'confirm_logout': 'Confirm logout',
        'confirm_logout_message': 'Are you sure you want to log out?',
        'logout': 'Logout',
        'store': 'Store',
        'browse_all_products': 'Browse all products',
        'browse_products_subtitle':
            'Find products faster, browse categories easily, and check prices more clearly.',
        'find_product': 'Find Product',
        'products_available': 'products available',
        'products_grouped_clearly':
            'Products are grouped clearly so prices and discounts are easier to scan.',
        'available': 'Available',
        'featured_now': 'Featured now',
        'out_of_stock': 'Out of stock',
        'see_product_details': 'See product details on the next page.',
        'selected_product_presentation':
            'Selected product with a clearer storefront presentation.',
        'discount_available': 'Discount available',
        'unable_add_item_cart': 'Unable to add item to cart',
        'alert': 'Alert',
        'secure_shopping': 'Secure shopping',
        'fast_delivery': 'Fast delivery',
        'best_prices': 'Best prices',
        'welcome_back': 'Welcome back',
        'reels_stories': 'Reels Stories',
        'watch_all': 'Watch All',
        'popular_products': 'Popular Products',
        'view_all': 'View All',
        'special_sale_banner': 'Get your special sale',
        'up_to': 'Up to',
        'shop_now': 'Shop now',
        'all_label': 'All',
        'new_collection': 'New Collection',
        'profile_title': 'Profile',
        'unable_open_profile': 'Unable to open profile right now',
        'notifications_title': 'Notifications',
        'no_notifications_yet': 'No notifications yet',
        'no_videos_available': 'No videos available',
        'live_virtual_try_on': 'Live virtual try-on',
        'savir_collection': 'Savir Collection',
        'video_fallback_subtitle':
            'Discover details, styling ideas, and quick highlights for this look.',
        'leave_your_comment': 'Leave your comment',
        'comments_items': 'items',
        'start_conversation_reel':
            'Start the conversation and share your thoughts about this reel.',
        'replying_to': 'Replying to',
        'write_comment': 'Write a comment...',
        'reply': 'Reply',
        'add_favorite_success': 'Product added to favorites',
        'remove_favorite_success': 'Product removed from favorites',
        'unable_add_favorite': 'Unable to add product to favorites',
        'unable_remove_favorite': 'Unable to remove product from favorites',
        'search_products_hint': 'Search products, brands, categories...',
        'search': 'Search',
        'items_label': 'Items',
        'special_offers': 'Special offers',
        'shop_top_products': 'Shop top products',
        'featured_products_subtitle':
            'Find featured products, clear prices, and quick access to the sections you need.',
        'available_now': 'available now',
        'no_results_found': 'No results found',
        'verify_code_title': 'Verify Code',
        'verify_code_subtitle':
            'Confirm your account using the code sent to your email.',
        'account_verification': 'Account verification',
        'enter_5_digit_activation':
            'Enter the 5-digit verification code to activate your account.',
        'resend_code': 'Resend code',
        'check_email': 'Check Email',
        'email_code_subtitle':
            'Enter the verification code sent to your email.',
        'verify_your_email': 'Verify your email',
        'use_5_digit_reset':
            'Use the 5-digit code to continue resetting your password.',
        'verify_code_incorrect': 'Verify code is incorrect',
        'profile_default_user': 'User',
        'account_info': 'Account information',
        'quick_actions': 'Quick actions',
        'change_profile_photo': 'Change profile photo',
        'addresses': 'Addresses',
        'phone_label': 'Phone',
        'account_id': 'Account ID',
        'profile_photo_updated': 'Profile photo updated successfully',
        'profile_photo_update_failed': 'Failed to upload image',
        'unable_update_follow_status': 'Unable to update follow status',
        'chat_ready_open_from_chat':
            'Chat is ready. Open it from the Chat page.',
        'chat_ready_short': 'Chat is ready.',
        'unable_start_chat': 'Unable to start chat',
        'no_users_found_yet': 'No users found yet.',
        'followers_label': 'Followers',
        'following_label': 'Following',
        'follow_label': 'Follow',
        'message_label': 'Message',
        'points_label': 'Points',
        'posts_label': 'Posts',
        'custom_label': 'custom',
        'saved_label': 'saved',
        'saved_perfumes': 'Saved Perfumes',
        'custom_perfumes': 'Custom Perfumes',
        'create_new': 'Create New',
        'collection_label': 'Collection',
        'settings_label': 'Settings',
        'edit_profile': 'Edit Profile',
        'order_history': 'Order History',
        'display_name': 'Display Name',
        'username_label': 'Username',
        'bio_label': 'Bio',
        'cancel_label': 'Cancel',
        'please_enter_display_name': 'Please enter a display name',
        'request_timed_out': 'Request timed out. Please try again.',
        'image_upload_failed_invalid_response':
            'Image upload failed: server returned invalid response',
        'image_upload_failed_prefix': 'Image upload failed',
        'unknown_error': 'Unknown error',
        'blend_label': 'Blend',
        'favorites_subtitle': 'Save products you want to revisit later.',
        'no_favorites_yet': 'No favorites yet',
        'favorites_empty_subtitle':
            'Products you like will show up here for quick access.',
        'saved_item': 'Saved item',
        'cart_title': 'Cart',
        'cart_subtitle':
            'Review products, adjust quantities, and continue to checkout.',
        'your_cart_empty': 'Your cart is empty',
        'cart_empty_subtitle':
            'Add products from the store and they will appear here.',
        'your_items': 'Your items',
        'products_ready_checkout': 'products ready for checkout',
        'checkout': 'Checkout',
        'product_details': 'Product details',
        'available_now_badge': 'Available now',
        'video_inline_not_supported': 'Inline video is not supported here.',
        'open_video': 'Open Video',
        'video_source_maybe_unsupported':
            'The source may be unsupported by the browser or Flutter Web.',
        'loading_video': 'Loading video...',
        'no_videos': 'No videos',
        'support': 'Support',
        'favorites': 'Favorites',
        'home': 'Home',
        'comment': 'Comment',
        'comments': 'Comments',
        'success_signup_title': 'Account created',
        'success_reset_password_title': 'Password changed',
        'go_to_login': 'Go to login',
        'warning': 'Warning',
        'phone_or_email_exists':
            'Phone number or email already exists. Please try another one.',
        'Home': 'Home',
        'Community': 'Community',
        'Builder': 'Builder',
        'Chat': 'Chat',
        'Cart': 'Cart',
        'Shopping Cart': 'Shopping Cart',
        'Proceed to Checkout': 'Proceed to Checkout',
        'Precious Collection': 'Precious Collection',
        'Precious Fragrance': 'Precious Fragrance',
        'Custom Perfume': 'Custom Perfume',
        'Promo Code': 'Promo Code',
        'Enter code': 'Enter code',
        'applied': 'applied',
        'off': 'off',
        'Order Summary': 'Order Summary',
        'Subtotal': 'Subtotal',
        'Shipping': 'Shipping',
        'Calculated at checkout': 'Calculated at checkout',
        'Savings': 'Savings',
        'Checkout': 'Checkout',
        'Place Order': 'Place Order',
        'No saved shipping address yet': 'No saved shipping address yet',
        'Add an address first so we can deliver your fragrance to the right location.':
            'Add an address first so we can deliver your fragrance to the right location.',
        'Add Address': 'Add Address',
        'Delivery Options': 'Delivery Options',
        'Standard Delivery': 'Standard Delivery',
        '5-7 business days': '5-7 business days',
        'Express Delivery': 'Express Delivery',
        '2-3 business days': '2-3 business days',
        'Premium Delivery': 'Premium Delivery',
        'Next day': 'Next day',
        'Cash on Delivery': 'Cash on Delivery',
        'Pay when your order arrives': 'Pay when your order arrives',
        'Credit Card': 'Credit Card',
        'Secure online payment': 'Secure online payment',
        'Please select a payment method': 'Please select a payment method',
        'Please select a order Type': 'Please select a order Type',
        'Payment init failed': 'Payment init failed',
        'Find your fragrance': 'Find your fragrance',
        'Discover Your Signature Scent': 'Discover Your Signature Scent',
        'luxury fragrances curated for a premium experience.':
            'luxury fragrances curated for a premium experience.',
        'Fragrances Available': 'Fragrances Available',
        'Browse refined scents, compare bottles, and discover your next signature perfume.':
            'Browse refined scents, compare bottles, and discover your next signature perfume.',
        'ok': 'OK',
      },
    };

    map['ar']!.addAll(_arOverrides);
    return map;
  }
}
